name: Ember Fan
favicon: null
layout_spectrum: 0.2414403900038451
typography_spectrum: 0.03017905866727233
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.30209272634238005
  lightness: 0.8842292104382068
  saturation: 0.3688221585471183
  rhythmicContrast: 0.6978886816650629
purpose: []
